Debenick,Tchadde | Change  link to a dropdown
GR8DI/gr8di.com pull request #9
Opened 2018-09-04 15:26 UTC by debenick17

2018-09-10 12:02 UTC, jlstrater requested changes

2018-09-10 12:02 UTC, jlstrater commented on package-lock.json
> +<<<<<<< Updated upstream
😞 It looks like you have some unresolved merge conflicts in here. Let me know if you need some help resolving them.

2018-09-10 12:02 UTC, jlstrater commented on src/app/internship/internship.component.html
> +                <h2 class="display-4">Meet the first badge of GR8DI Internship Program</h2>
badge -> batch

2018-09-10 12:02 UTC, jlstrater commented on src/app/internship/internship.component.html
> +              <p class="description" style="text-align:justify;">The groovy Summer Internship organised by GR8DI, is a program initiated to help students in the English speaking part of Cameroon to c
Add a space before Due.

2018-09-11 14:03 UTC, debenick17 commented on package-lock.json
> +<<<<<<< Updated upstream
Yeah, I need help resolving them

2018-09-11 14:03 UTC, debenick17 commented on src/app/internship/internship.component.html
> +                <h2 class="display-4">Meet the first badge of GR8DI Internship Program</h2>
Oh thanks

2018-09-11 14:04 UTC, debenick17 commented on src/app/internship/internship.component.html
> +              <p class="description" style="text-align:justify;">The groovy Summer Internship organised by GR8DI, is a program initiated to help students in the English speaking part of Cameroon to c
Alright

2018-09-11 15:38 UTC, merged